### PR TITLE
Fixed section being improperly written into

### LINKED ISSUE #152: wasm-transformer: output is invalid
Running the attached WASM binary through lowerI64Imports resulted in an invalid file. Wasmtime, wasm2wat, wasmer, wasmer-js all report that it is corrupted. Trying to `WebAssembly.instantiate()` the result gives `unknown section code #0x75 @+530`.

I was using the most recent version from master at the time of this post. This is the code snippet based on @wasmer/cli.

```js
const { lowerI64Imports } = require('@wasmer/wasm-transformer');

const fs = require('fs');

var bytes = fs.readFileSync('busy.wasm');
bytes = lowerI64Imports(bytes);

fs.writeFileSync('busy32.wasm', bytes);
```

[busy.zip](https://github.com/wasmerio/wasmer-js/files/3798848/busy.zip)

### PR DESCRIPTION
**Pull request by syrusakbary**
Fixed section being improperly written into.

This PR fixes #152

### CODE REVIEW

File: crates/wasm_transformer/src/applier.rs [hunk 1]
```diff
@@ -283,7 +283,7 @@ fn add_entries_to_section(
 
     // Number of Entries (AKA Count)
     let number_of_entries_position =
-        (starting_offset + (section.start_position as isize) + 1 + (section_length_bytes as isize))
```
Comment (torch2424) [inline crates/wasm_transformer/src/applier.rs]: 🤦‍♂ 😂 

Thanks for catching this! 😄
