### PR TITLE
Fixed up inherits, and prepared for deployment

### LINKED ISSUE #134: wasmfs: Cannot read property 'inherits' of undefined
This error occurs when running `require('@wasmer/wasmfs')` in Node (tested on v12.11.0 and v8.9.1), and in the browser with Browserify.

What is the proper way to import it?

### PR DESCRIPTION
**Pull request by torch2424**
closes #134 

This fixes a weird memfs circular dependency rollup did not like: https://github.com/webpack/webpack/issues/1019#issuecomment-296850308

# Example 

Screen Shot 2019-10-25 at 12 39 20 PM

### CODE REVIEW

File: examples/node-stubbed/index.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ const msleep = n => {
 };
 
 // Set up our file system (NOTE: We could use node's fs normally for this case)
-const wasmerFs = new WasmerFileSystem();
+const wasmerFs = new WasmerFileSystem.default();
```
Comment (syrusakbary) [inline examples/node-stubbed/index.js]: ?

File: package.json [hunk 2]
```diff
@@ -72,7 +72,7 @@
     "rollup-plugin-copy": "^3.1.0",
     "rollup-plugin-hash": "^1.3.0",
     "rollup-plugin-json": "^4.0.0",
-    "rollup-plugin-node-builtins": "^2.1.2",
+    "rollup-plugin-node-builtins": "git+https://github.com/torch2424/rollup-plugin-node-builtins.git",
```
Comment (syrusakbary) [inline package.json]: Can we have this in the wasmerio org?

File: examples/node-stubbed/index.js (hunk 1 above)
Comment (torch2424) [reply examples/node-stubbed/index.js]: This is because the file system has a default export, but in node this is an object, so you gotta use default to access efault export.

`const { WasmFs } = require('wasmfs')` works as well 😄

File: package.json (hunk 2 above)
Comment (torch2424) [reply package.json]: Sure! Let's do that adfter we get a working fix for @corwin-of-amber 😄

**Comment by corwin-of-amber** [comment]
Funny, I just did almost the very same fixes in my working copy in order to use rollup. Did not occur to me the two problems were related.

File: package.json (hunk 2 above)
Comment (syrusakbary) [reply package.json]: Actually, I just did!

```suggestion
    "rollup-plugin-node-builtins": "git+https://github.com/wasmerio/rollup-plugin-node-builtins.git",
```
